### PR TITLE
The var directory is now used for the cache instead of nested

### PR DESCRIPTION
**Pull request by iltar**
Instead of nesting all geberated logs/cache stuff somewhere deep in the structure, put it in the var directory in the project root.

### CODE REVIEW

**Comment by nicoschoenmaker** [comment]
:+1:

**Comment by xabbuh** [comment]
@iltar You may now want to create an empty `/var` directory to ensure that it is always writable?

**Comment by iltar** [comment]
Whenever I do `rm -rf var`, it will just be created when I run phpunit, isn't that enough?

**Comment by xabbuh** [comment]
But can you always be sure that the bundle directory itself is writable?

**Comment by iltar** [comment]
Just as sure as in the old-case, except that it wrote it somewhere deeply nested in the test directory structure.

Are there any easy ways to avoid issues where the permissions would be incorrect or is it more hassle than worth the fix? This is only the case for people who want to run the tests and worse case-scenario they can push and have travis run it without problems.

**Pull request merged**
