### PR TITLE
execute the required PHPUnit version in CI builds

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by iltar** [comment]
:+1: thanks!

**Comment by xabbuh** [comment]
Oh, you were too fast. :/ I was just pushing a better commit message. :D

**Comment by xabbuh** [comment]
Anyway, for further reference: https://github.com/sebastianbergmann/phpunit/issues/1882#issuecomment-144650815

**Comment by iltar** [comment]
Ah didn't check the PR time (just woke up). I'm glad someone is pushing the versions up a notch.

**Comment by xabbuh** [comment]
It's not such a big deal. :)

**Pull request merged**
